//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingAppFB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerProductDetail
    {
        public int BId { get; set; }
        public string BuyerID { get; set; }
        public string SellerID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string ItemCategory { get; set; }
        public string ItemDescription { get; set; }
        public string Total { get; set; }
        public string ItemName { get; set; }
    }
}
