//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingAppFB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellProductDetail
    {
        public string SellerID { get; set; }
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemCategory { get; set; }
        public string ItemPrice { get; set; }
        public string ItemDescription { get; set; }
        public byte[] ItemImage { get; set; }
    }
}
